function getName(){
/* Substracting 1 from array length here because arrays are 0 index so 
        even though there are 200 names name 200 is at index 199 */
  const randomNumber = Math.floor(Math.random() * arrOfNames.length - 1);
  // grabbing name from the array using random number as index
  // and saving into a variable for better readability
  const name = arrOfNames[randomNumber];
  // returning grabbed name
  return name;
}

function renderName() {
    // getting name returned by above function and storing it
    // into variable for usage
    const name = getName();
    // grabbing the html node where we will display our names
    const nameDiv = document.getElementById("brian-name-div");
    // we update the element by changing setting the innerHTML content to what we want
    // in this case the name
    nameDiv.innerHTML = name
}

/**
 * Array of 200 most comon male and female names
 */
const arrOfNames = [
  "James",
  "Mary",
  "Robert",
  "Patricia",
  "John",
  "Jennifer",
  "Michael",
  "Linda",
  "William",
  "Elizabeth",
  "David",
  "Barbara",
  "Richard",
  "Susan",
  "Joseph",
  "Jessica",
  "Thomas",
  "Sarah",
  "Charles",
  "Karen",
  "Christopher",
  "Nancy",
  "Daniel",
  "Lisa",
  "Matthew",
  "Betty",
  "Anthony",
  "Margaret",
  "Mark",
  "Sandra",
  "Donald",
  "Ashley",
  "Steven",
  "Kimberly",
  "Paul",
  "Emily",
  "Andrew",
  "Donna",
  "Joshua",
  "Michelle",
  "Kenneth",
  "Dorothy",
  "Kevin",
  "Carol",
  "Brian",
  "Amanda",
  "George",
  "Melissa",
  "Edward",
  "Deborah",
  "Ronald",
  "Stephani",
  "Timothy",
  "Rebecca",
  "Jason",
  "Sharon",
  "Jeffrey",
  "Laura",
  "Ryan",
  "Cynthia",
  "Jacob",
  "Kathleen",
  "Gary",
  "Amy",
  "Nicholas",
  "Shirley",
  "Eric",
  "Angela",
  "Jonatha",
  "Helen",
  "Stephen",
  "Anna",
  "Larry",
  "Brenda",
  "Justin",
  "Pamela",
  "Scott",
  "Nicole",
  "Brandon",
  "Emma",
  "Benjami",
  "Samanth",
  "Samuel",
  "Katherine",
  "Gregory",
  "Christine",
  "Frank",
  "Debra",
  "Alexander",
  "Rachel",
  "Raymond",
  "Catherine",
  "Patrick",
  "Carolyn",
  "Jack",
  "Janet",
  "Dennis",
  "Ruth",
  "Jerry",
  "Maria",
  "Tyler",
  "Heather",
  "Aaron",
  "Diane",
  "Jose",
  "Virginia",
  "Adam",
  "Julie",
  "Henry",
  "Joyce",
  "Nathan",
  "Victoria",
  "Douglas",
  "Olivia",
  "Zachary",
  "Kelly",
  "Peter",
  "Christina",
  "Kyle",
  "Lauren",
  "Walter",
  "Joan",
  "Ethan",
  "Evelyn",
  "Jeremy",
  "Judith",
  "Harold",
  "Megan",
  "Keith",
  "Cheryl",
  "Christian",
  "Andrea",
  "Roger",
  "Hannah",
  "Noah",
  "Martha",
  "Gerald",
  "Jacqueline",
  "Carl",
  "Frances",
  "Terry",
  "Gloria",
  "Sean",
  "Ann",
  "Austin",
  "Teresa",
  "Arthur",
  "Kathryn",
  "Lawrenc",
  "Sara",
  "Jesse",
  "Janice",
  "Dylan",
  "Jean",
  "Bryan",
  "Alice",
  "Joe",
  "Madison",
  "Jordan",
  "Doris",
  "Billy",
  "Abigail",
  "Bruce",
  "Julia",
  "Albert",
  "Judy",
  "Willie",
  "Grace",
  "Gabriel",
  "Denise",
  "Logan",
  "Amber",
  "Alan",
  "Marilyn",
  "Juan",
  "Beverly",
  "Wayne",
  "Danielle",
  "Roy",
  "Theresa",
  "Ralph",
  "Sophia",
  "Randy",
  "Marie",
  "Eugene",
  "Diana",
  "Vincent",
  "Brittany",
  "Russell",
  "Natalie",
  "Elijah",
  "Isabella",
  "Louis",
  "Charlotte",
  "Bobby",
  "Rose",
  "Philip",
  "Alexis",
  "Johnny",
  "Kayla",
];
